### ISSUE TITLE
Error when loading extension

### ISSUE THREAD

**Issue by ambrose-leung** [roberchi/Chino.Jupyter.Extensions#1]
just fyi - Not sure why this is happening on my machine
`#r "nuget:Chino.Jupyter.Extensions,1.0.4-beta"`

```
Error: System.TypeLoadException: Method 'OnLoadAsync' in type 'Chino.Jupiter.Extensions.ImportExtension' from assembly 'Chino.Jupyter.Extensions, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 112
   at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembliesInDirectory(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 74
   at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromDirectoryAsync(DirectoryInfo directory, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 47
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensionsFromDirectoryAsync(DirectoryInfo directory, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 308
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 148
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 72
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 44
```

**Comment by ambrose-leung** [comment]
I've made a PR that fixes this - https://github.com/roberchi/Chino.Jupyter.Extensions/pull/2 - .NET Interactive nuget libraries were updated, they made breaking changes to old extensions.
